In [7]:
import numpy as np
#braodcasting 간단
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]
             ])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [8]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [10]:
percentage = 100*A/cal.reshape(1,4) #사실 cal는 이미 A.sum을 통해 1x4행렬이 되었으니
                                    #굳이 reshape해줄 필요는 없음
                                    #reshape은 상수시간이 걸려 호출이 굉장히 cheap
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [11]:
#numpy 사용법
a = np.random.randn(5)
print(a)

[ 0.41700274  0.29008266  1.03029146 -0.78514092  0.13342219]


In [13]:
print(a.shape) #rank가 1인 행렬으로 행벡터도 열벡터도 아님

(5,)


In [14]:
print(a.T)#그래서 직관적이지 않은 결과를 도출하게 됨

[ 0.41700274  0.29008266  1.03029146 -0.78514092  0.13342219]


In [15]:
print(np.dot(a,a.T)) #행렬이 나와야할 것 같지만 하나의 수만 나옴
#그래서 neuralNet을 구할 땐 (n,)인 랭크가 1인 배열을 아예 사용 X

1.9537874614780706


In [16]:
a = np.random.randn(5,1)#5x1 열벡터가 됨
                        #열벡터나 행벡터를 사용하자
                        #assert함수를 통해 행렬과 배열의 차원을 체크
                        #행렬과 벡터를 필요한 차원으로 만들기 위해 reshape함수를 자주 사용
print(a)

[[ 0.74930096]
 [ 0.98942612]
 [-0.50672975]
 [-2.13342764]
 [-1.34041978]]


In [17]:
print(a.T)

[[ 0.74930096  0.98942612 -0.50672975 -2.13342764 -1.34041978]]


In [18]:
print(np.dot(a,a.T))

[[ 0.56145192  0.74137794 -0.37969308 -1.59857937 -1.00437782]
 [ 0.74137794  0.97896404 -0.50137165 -2.11086903 -1.32624634]
 [-0.37969308 -0.50137165  0.25677504  1.08107125  0.67923058]
 [-1.59857937 -2.11086903  1.08107125  4.55151349  2.85968862]
 [-1.00437782 -1.32624634  0.67923058  2.85968862  1.7967252 ]]
